### ISSUE TITLE
Specify Alternate wwwroot

### ISSUE THREAD

**Issue by jamiejackson** [Ortus-Solutions/docker-commandbox#5]
In SCM, I have a bunch of directories at the same level as wwwroot; e.g.:

```
deployment_root
├──wwwroot
├──foo
├──bar
├──model
└──...
```

So I think I want to be able to do something like:

```yml
...
    environment:
      WWWROOT: "/app/wwwroot"
    volumes:
      - /Users/jjackson/projects/project_a/cfml/deployment_root:/app
...
```

Is there already a way to do this that I'm overlooking?

**Comment by lmajano** [comment]
Jamie
You can mount multiple directories into the image but only one directory can be the web root. What is the purpose of the other folders

**Comment by jamiejackson** [comment]
I've got directories like, `model`, `lib`, `test`, etc. that are at the same level as `wwwroot`--directories used by the app, but outside of the web root. I would guess that I'm not the only one with applications that have a similar structure.

I forgot that I had to do a trick even with the official Lucee image:

Dockerfile
```Dockerfile
RUN \
  set -x \
  mkdir -p /var/www/app \
  && sed \
    -i 's+<Context path="" docBase="/var/www/">+<Context path="" docBase="/var/www/wwwroot">+' \
    '/usr/local/tomcat/conf/server.xml'
```

docker-compose.yml
```yaml
  lucee:
...
    volumes:
      - ./deployment_root:/var/www
...
```
... but I'm not Undertow-savvy, so I don't know how to do a similar trick with it.
